version: '3.8'

################################################################################
# Media Players Stack
# 
# This stack includes:
# - Plex Media Server: Popular media streaming platform
# - Jellyfin: Open-source media server
# - Navidrome: Modern music server and streamer
#
# Configuration storage: NFS shared storage (/nfs/vm_shares/cyrene)
# Media files: CIFS/SMB mount (/mnt/media)
################################################################################

services:
  #############################################################################
  # Plex Media Server
  # Web UI: http://<your-server>:32400/web
  # Documentation: https://hub.docker.com/r/linuxserver/plex
  #############################################################################
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    restart: unless-stopped
    networks:
      - media-players
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York  # Change to your timezone
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}  # Optional: Get from https://www.plex.tv/claim/
    volumes:
      # Config on NFS share
      - /nfs/vm_shares/cyrene/apps/plex/config:/config
      # Media from CIFS mount
      - /mnt/media:/media:ro  # Read-only access to media
      # Optional: Transcode directory (can be local for better performance)
      - /nfs/vm_shares/cyrene/apps/plex/transcode:/transcode
    ports:
      - "32400:32400"  # Plex Web UI
      - "1900:1900/udp"  # DLNA
      - "5353:5353/udp"  # Bonjour/Avahi
      - "8324:8324"  # Plex for Roku
      - "32410:32410/udp"  # GDM network discovery
      - "32412:32412/udp"  # GDM network discovery
      - "32413:32413/udp"  # GDM network discovery
      - "32414:32414/udp"  # GDM network discovery
      - "32469:32469"  # Plex DLNA Server
    devices:
      # Fix libusb_init error - grants access to USB devices
      - /dev/bus/usb:/dev/bus/usb
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "dockpeek.tags=media,streaming"
      - "dockpeek.description=Plex Media Server"
      - "dockpeek.icon=https://www.plex.tv/wp-content/uploads/2018/01/plex-icon.svg"

  #############################################################################
  # Jellyfin Media Server
  # Web UI: http://<your-server>:8096
  # Documentation: https://hub.docker.com/r/linuxserver/jellyfin
  #############################################################################
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    networks:
      - media-players
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York  # Change to your timezone
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}  # Optional: Your public URL
    volumes:
      # Config on NFS share
      - /nfs/vm_shares/cyrene/apps/jellyfin/config:/config
      # Cache on NFS share
      - /nfs/vm_shares/cyrene/apps/jellyfin/cache:/cache
      # Media from CIFS mount
      - /mnt/media:/media:ro  # Read-only access to media
    ports:
      - "8096:8096"  # HTTP web UI
      - "8920:8920"  # HTTPS web UI (optional)
      - "7359:7359/udp"  # Discovery (optional)
    #devices:
      # Optional: Hardware transcoding support
      # Uncomment the appropriate line for your hardware:
      # Intel Quick Sync:
      # - /dev/dri:/dev/dri
      # NVIDIA GPU:
      # - /dev/nvidia0:/dev/nvidia0
      # - /dev/nvidiactl:/dev/nvidiactl
      # - /dev/nvidia-modeset:/dev/nvidia-modeset
      # - /dev/nvidia-uvm:/dev/nvidia-uvm
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "dockpeek.tags=media,streaming"
      - "dockpeek.description=Jellyfin Media Server"
      - "dockpeek.icon=https://jellyfin.org/images/logo.svg"

  #############################################################################
  # Navidrome Music Server
  # Web UI: http://<your-server>:4533
  # Documentation: https://www.navidrome.org/
  #############################################################################
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    hostname: navidrome
    restart: unless-stopped
    networks:
      - media-players
    environment:
      - PUID=1000
      - PGID=1000
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
    volumes:
      # Config/database on NFS share
      - /nfs/vm_shares/cyrene/apps/navidrome:/data
      # Music from CIFS mount
      - /mnt/media/music:/music:ro
    ports:
      - "4533:4533"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "dockpeek.tags=media,music,streaming"
      - "dockpeek.description=Modern Music Server and Streamer"
      - "dockpeek.icon=https://raw.githubusercontent.com/navidrome/navidrome/master/resources/logo-192x192.png"

################################################################################
# Networks
################################################################################
networks:
  media-players:
    name: media-players
    driver: bridge

################################################################################
# Notes:
# 
# 1. All services use bridge network mode for Nginx Proxy Manager compatibility
# 2. UDP port 1900 (DLNA) is used by Plex only (removed from Jellyfin to avoid conflict)
# 3. All services mount /mnt/media as read-only (configure with setup-cifs-media.sh)
# 4. Config stored on NFS for easy backup and migration
# 5. For hardware transcoding (Plex/Jellyfin), uncomment appropriate device mappings
# 6. Change timezone (TZ) to match your location
# 
# Navidrome Features:
# - Subsonic API compatible (works with mobile apps like DSub, Ultrasonic, Symfonium)
# - Modern web player with lyrics support
# - Multi-user support with individual libraries
# - Smart playlists and radio mode
# - Scrobbling to Last.fm/ListenBrainz
# 
# Media Organization:
# /mnt/media/
#   ├── tv/         - TV Shows (Plex/Jellyfin)
#   ├── movies/     - Movies (Plex/Jellyfin)
#   ├── music/      - Music (Plex/Jellyfin/Navidrome)
#   ├── books/      - Audiobooks/Ebooks
#   └── downloads/  - Downloads from *arr apps
################################################################################
