services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/New_York}
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
    ports:
      - "3000:3000"
    volumes:
      - /nfs/vm_shares/herta/apps/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - homepage
      - nginx-proxy-manager
    labels:
      - "dockpeek.tags=dashboard,startpage"

networks:
  homepage:
    driver: bridge
  nginx-proxy-manager:
    external: true
