services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
      - HOMEPAGE_VAR_HOST_IP=${HOMEPAGE_VAR_HOST_IP}
      - HOMEPAGE_VAR_PLEX_TOKEN=${HOMEPAGE_VAR_PLEX_TOKEN}
      - HOMEPAGE_VAR_JELLYFIN_API_KEY=${HOMEPAGE_VAR_JELLYFIN_API_KEY}
      - HOMEPAGE_VAR_NAVIDROME_USER=${HOMEPAGE_VAR_NAVIDROME_USER}
      - HOMEPAGE_VAR_NAVIDROME_TOKEN=${HOMEPAGE_VAR_NAVIDROME_TOKEN}
      - HOMEPAGE_VAR_NAVIDROME_SALT=${HOMEPAGE_VAR_NAVIDROME_SALT}
    volumes:
      - ${HOMEPAGE_CONFIG}:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${HOMEPAGE_PORT:-3001}:3000"
    networks:
      - homelab

networks:
  homelab:
    external: true
