services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/New_York}
      - PASSWORD=${CODE_SERVER_PASSWORD}
      - SUDO_PASSWORD=${CODE_SERVER_SUDO_PASSWORD}
      - PROXY_DOMAIN=${CODE_SERVER_PROXY_DOMAIN}
    ports:
      - "8443:8080"
    volumes:
      - /nfs/vm_shares/herta/apps/code-server/config:/home/coder/.config
      - /nfs/vm_shares/herta/apps/code-server/projects:/home/coder/projects
      - /nfs/vm_shares:/nfs/vm_shares
    restart: unless-stopped
    networks:
      - code-server
      - nginx-proxy-manager
    labels:
      - "dockpeek.tags=development,ide"

networks:
  code-server:
    driver: bridge
  nginx-proxy-manager:
    external: true
