services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    environment:
      - TZ=${TZ:-America/New_York}
      - PORT=8080
    ports:
      - "8282:8080"
    volumes:
      - termix-data:/app/data
    restart: unless-stopped
    networks:
      - termix
      - nginx-proxy-manager
    labels:
      - "dockpeek.tags=ssh,terminal,management"

networks:
  termix:
    driver: bridge
  nginx-proxy-manager:
    external: true

volumes:
  termix-data:
    driver: local
