version: '3.8'

################################################################################
# Utilities Stack
# 
# This stack includes:
# - Speedtest Tracker: Internet speed monitoring
# - IT-Tools: Collection of handy developer tools
# - Cyberchef: Data analysis and transformation tool
# - Excalidraw: Virtual whiteboard for sketching diagrams
# - Stirling-PDF: Powerful PDF manipulation tool
#
# Configuration storage: NFS shared storage (/nfs/vm_shares/herta)
################################################################################

services:
  #############################################################################
  # Speedtest Tracker
  # Web UI: http://<your-server>:8765
  # Documentation: https://docs.speedtest-tracker.dev/
  #############################################################################
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    restart: unless-stopped
    networks:
      - utilities
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - APP_KEY=${SPEEDTEST_APP_KEY:-base64:cGxlYXNlQ2hhbmdlVGhpc0tleVRvU29tZXRoaW5nU2VjdXJl}  # Change this!
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=0 */6 * * *  # Run every 6 hours
      - SPEEDTEST_SERVERS=  # Leave empty for auto-select
      - PRUNE_RESULTS_OLDER_THAN=365  # Days to keep results
    volumes:
      - speedtest-tracker-config:/config
    ports:
      - "8765:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "dockpeek.tags=utilities,network"
      - "dockpeek.description=Internet Speed Monitoring"
      - "dockpeek.icon=https://raw.githubusercontent.com/alexjustesen/speedtest-tracker/main/.github/logo.png"

  #############################################################################
  # IT-Tools
  # Web UI: http://<your-server>:8766
  # Documentation: https://github.com/CorentinTh/it-tools
  #############################################################################
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    hostname: it-tools
    restart: unless-stopped
    networks:
      - utilities
    ports:
      - "8766:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "dockpeek.tags=utilities,development"
      - "dockpeek.description=Handy Developer Tools Collection"
      - "dockpeek.icon=https://raw.githubusercontent.com/CorentinTh/it-tools/main/public/favicon.ico"

  #############################################################################
  # CyberChef
  # Web UI: http://<your-server>:8767
  # Documentation: https://github.com/gchq/CyberChef
  #############################################################################
  cyberchef:
    image: mpepping/cyberchef:latest
    container_name: cyberchef
    hostname: cyberchef
    restart: unless-stopped
    networks:
      - utilities
    ports:
      - "8767:8000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "dockpeek.tags=utilities,security"
      - "dockpeek.description=Cyber Swiss Army Knife"
      - "dockpeek.icon=https://raw.githubusercontent.com/gchq/CyberChef/master/src/web/static/images/logo/cyberchef.svg"

  #############################################################################
  # Excalidraw
  # Web UI: http://<your-server>:8768
  # Documentation: https://github.com/excalidraw/excalidraw
  #############################################################################
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    hostname: excalidraw
    restart: unless-stopped
    networks:
      - utilities
    ports:
      - "8768:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "dockpeek.tags=utilities,design"
      - "dockpeek.description=Virtual Whiteboard for Sketching"
      - "dockpeek.icon=https://excalidraw.com/favicon.ico"

  #############################################################################
  # Dozzle
  # Web UI: http://<your-server>:8770
  # Documentation: https://dozzle.dev/
  #############################################################################
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    hostname: dozzle
    restart: unless-stopped
    networks:
      - utilities
    environment:
      - DOZZLE_LEVEL=info
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER=status=running
      - DOZZLE_NO_ANALYTICS=true
      # Multi-host configuration - add your Docker hosts here
      # Format: tcp://hostname:port or unix:///var/run/docker.sock
      # Make sure Docker TCP API is exposed on remote hosts (port 2375)
      - DOZZLE_REMOTE_HOST=${DOZZLE_REMOTE_HOST}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8770:8080"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "dockpeek.tags=utilities,monitoring"
      - "dockpeek.description=Real-time Docker Log Viewer"
      - "dockpeek.icon=https://dozzle.dev/assets/logo.png"

  #############################################################################
  # FileBrowser
  # Web UI: http://<your-server>:8771
  # Documentation: https://filebrowser.org/
  #############################################################################
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    hostname: filebrowser
    restart: unless-stopped
    networks:
      - utilities
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /nfs/vm_shares:/srv/nfs
      - filebrowser-config:/config
    ports:
      - "8771:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "dockpeek.tags=utilities,files"
      - "dockpeek.description=Web-based File Manager"
      - "dockpeek.icon=https://raw.githubusercontent.com/filebrowser/logo/master/icon.svg"

################################################################################
# Networks
################################################################################
networks:
  utilities:
    name: utilities
    driver: bridge

################################################################################
# Volumes
################################################################################
volumes:
  speedtest-tracker-config:
    name: speedtest-tracker-config
    driver: local
  filebrowser-config:
    name: filebrowser-config
    driver: local

################################################################################
# Notes:
# 
# Utilities Included:
# 
# 1. Speedtest Tracker (8765)
#    - Automated internet speed tests
#    - Historical data and charts
#    - Notifications for speed drops
# 
# 2. IT-Tools (8766)
#    - 80+ developer tools in one place
#    - Base64, JWT, UUID generators
#    - Hash calculators, converters
#    - No data leaves your browser
# 
# 3. CyberChef (8767)
#    - Data encoding/decoding
#    - Encryption/decryption
#    - Data analysis and manipulation
#    - 300+ operations available
# 
# 4. Excalidraw (8768)
#    - Hand-drawn style diagrams
#    - Real-time collaboration
#    - Export to PNG, SVG
#    - Network diagrams, flowcharts
# 
# 5. Dozzle (8770)
#    - Real-time log viewing
#    - Multi-host support
#    - Search and filter logs
#    - Lightweight and fast
# 
# 6. FileBrowser (8771)
#    - Browse NFS share via web
#    - Upload/download files
#    - Create, edit, delete files
#    - User management
################################################################################
