---
- Quick links:
    - DuckDNS:
        - href: https://www.duckdns.org
    - TrueNAS:
        - href: http://truenas.local
    - Docker Hub:
        - href: https://hub.docker.com
    - LinuxServer.io:
        - href: https://www.linuxserver.io
