---
- Music:
    - Navidrome:
        icon: navidrome.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:4533
        description: Music streaming server
        widget:
          type: navidrome
          url: http://navidrome:4533
          user: "{{HOMEPAGE_VAR_NAVIDROME_USER}}"
          token: "{{HOMEPAGE_VAR_NAVIDROME_TOKEN}}"
          salt: "{{HOMEPAGE_VAR_NAVIDROME_SALT}}"

- Media:
    - Plex:
        icon: plex.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:32400/web
        description: Media server
        widget:
          type: plex
          url: http://plex:32400
          key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"

    - Jellyfin:
        icon: jellyfin.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:8096
        description: Open-source media server
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
          enableBlocks: true
          enableNowPlaying: true
