services:
  # Dockpeek - Lightweight Docker dashboard
  dockpeek:
    image: dockpeek/dockpeek:latest
    container_name: dockpeek
    environment:
      - SECRET_KEY=${DOCKPEEK_SECRET_KEY}
      - USERNAME=${DOCKPEEK_USERNAME:-admin}
      - PASSWORD=${DOCKPEEK_PASSWORD:-admin}
      - TZ=${TZ:-America/New_York}
      
      # Docker Host 1 (Local)
      - DOCKER_HOST_1_URL=unix:///var/run/docker.sock
      - DOCKER_HOST_1_NAME=${DOCKER_HOST_1_NAME:-Local}
      # - DOCKER_HOST_1_PUBLIC_HOSTNAME=${DOCKER_HOST_1_PUBLIC_HOSTNAME}
      
      # Docker Host 2 (Remote) - Uncomment and configure to add
      # - DOCKER_HOST_2_URL=${DOCKER_HOST_2_URL}
      # - DOCKER_HOST_2_NAME=${DOCKER_HOST_2_NAME:-Remote Server}
      # - DOCKER_HOST_2_PUBLIC_HOSTNAME=${DOCKER_HOST_2_PUBLIC_HOSTNAME}
      
      # Docker Host 3 - Add more hosts as needed
      # - DOCKER_HOST_3_URL=${DOCKER_HOST_3_URL}
      # - DOCKER_HOST_3_NAME=${DOCKER_HOST_3_NAME}
      # - DOCKER_HOST_3_PUBLIC_HOSTNAME=${DOCKER_HOST_3_PUBLIC_HOSTNAME}
      
      # Configuration
      - TRAEFIK_LABELS=true
      - TAGS=true
      - PORT_RANGE_GROUPING=true
      - TRUST_PROXY_HEADERS=true
      - TRUSTED_PROXY_COUNT=1
      - DOCKER_CONNECTION_TIMEOUT=2
    ports:
      - "3420:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - monitoring
      - nginx-proxy-manager
    labels:
      - "dockpeek.tags=monitoring,docker"

networks:
  monitoring:
    name: monitoring
    driver: bridge
  nginx-proxy-manager:
    name: nginx-proxy-manager
    external: true
